spring:
  config:
    import: optional:file:.env                        # optional : .env 파일이 없더라도 컴파일 에러가 발생 X
                                                      # file : 파일을 import 하겠다
                                                      # .env : 파일명
  application:
    name: GreengramVer3
  jackson:
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_v3tdd    # 데이터 베이스 이름
    username: root                # 아이디
    password: green502            # 비밀번호

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB

mybatis:
  mapper-locations: mappers/**/*.xml     # resources 아래에 xml 담긴 (mappers) 폴더이름

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui: # swagger UI 설정
    path: /swagger    # localhost:8080/swagger 로 접속할 수 있게 설정  (redirect)
    operations-sorter: method   # alpha (default) : url 기준 정렬, method : http - method 기준 정렬
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true   #try it out 을 했을때 request duration(처리 소요시간)을 추가로 찍어줌
  cache:
    disabled: true

file:
  directory: D:/2024-1/download/greengram_ver3tdd/       #    절대 주소값 저장

# custom 속성 지정
app:
  jwt:
    # JWT 만들 때 사용하는 키(암호화) -> 나중에 복호화 할때도 사용
    secret: DaeguGreenArtAcademyClass502RoomForSpringBootFightingsdkfjslkjflksajdffdskljdkdjfkasdfiagfddfdfddd   # 키 값 : value 값

    # front - back 간 JWT 받는 헤더 키 이름
    header-schema-name: authorization

    # 토큰의 종류: Bearer 는 JWT or OAuth2.0(소셜 로그인)를 의미
    token-type: Bearer


    # AT(Access-Token) - 만료 시간 (ms -> 2시간)
    access-token-expiry: 30000
    # 1800000 : 30분

    # RT(Refresh-Token) - 만료시간(ms) - 15일
    refresh-token-expiry: 1296000000

management:
  endpoint:               # 엔드 포인트 (URL)
    health:
      show-details: always      # http://localhost:8080/actuator/health 정보를 추가로 더 보여줌 (디테일한 정보)

  endpoints:              # 전체 엔드 포인트 세팅
    web:
      exposure:
        include: "*"      # actuator의 모든 엔드 포인트를 웹에 노출  (http://localhost:8080/actuator)
  info:                   # 엔드 포인트 이지만 endpoint 아래에 있지 않고, management 아래에 위치
    java:
      enabled: true       # http://localhost:8080/actuator/info 값 뜨게 해줌
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080            # 로컬로만 접속해야 접속가능






---                       #  --- : 파일안에서 분리 해줌 (위쪽은 프로필 설정 x)
spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_v3tdd_test
  sql:
    init:
      mode: always    # tdd 프로필을 쓸때 매번 data.sql, schema.sql 을 실행 하겠다는 의미
                      # edit configurations -> profile active 칸에 프로필 이름 입력 하면 됨



---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_odd_first_4
    username: odd_first_4
    password: cell
file:
  directory: /home/download   # 혹시나 파일 업로드가 있다면

                              # 설정 완료 -> 우측 상단 코끼리 -> Tasks -> build -> bootJar 실행
                              # -> 좌측 파일 탐색기에 주황build -> ilbs -> jar파일

  # jar 파일 경로 복사 -> cmd -> cd 경로값(엔터) -> D:(엔터) -> java -jar jar파일명  --spring.profiles.active=prod(엔터)

  # 다른 작업할때는 상단 실행버튼 좌측 화살표 클릭 -> Edit Configurations -> active profiles 값 수정



